---
# tasks file for render_nodes
- include_tasks: "{{ render_nodes_tasks }}"
  loop:
    - config_deadline_client.yml
    - config_media_encoder.yml
    - config_ffmpeg.yml
  loop_control:
    loop_var: render_nodes_tasks