---
# tasks file for render_manager
- include_tasks: "{{ render_manager_tasks }}"
  loop:
    - configure_deadline_repository.yml
    - install_files.yml
  loop_control:
    loop_var: render_manager_tasks