---

- name: Create {{ content_user }} User
  win_user:
    name: "{{ content_user }}"
    password: "{{ content_password }}"
    fullname: "{{ content_user }}"
    user_cannot_change_password: true
    groups:
      - Administrators

- name: Hide {{ project_user }} User
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\SpecialAccounts\Userlist
    name: "{{ project_user }}"
    type: dword
    data: 0