---

- name: Create {{ location_name }} Delivery Folder
  win_file:
    path: "{{ delivery_folder }}"
    state: directory

- name: Set Delivery Folder Permissions for {{ content_user }}
  win_acl:
    path: "{{ delivery_folder }}"
    user: "{{ content_user }}"
    type: deny
    rights: Write, Delete, DeleteSubdirectoriesAndFiles
    state: present

- name: Share {{ location_name }} Delivery Folder
  win_share:
    name: "{{ location_name }} Delivery"
    description: Folder for local delivery of assets for {{ location_name }}
    path: "{{ delivery_folder }}"
    full: "Everyone"
    state: present