--- 

- name: Remove any existing M drive mapping
  win_mapped_drive:
    letter: M
    state: absent

- name: Map Stages Stock Content Drive
  block:
    - name: Save the network credentials
      win_credential:
        name: "{{ hostvars['workstation_4']['ansible_host'] }}"
        type: domain_password
        username: "{{ content_user }}"
        secret: "{{ content_password }}"
        state: present

    - name: Map Stages Stock Content Drive
      win_mapped_drive:
        letter: M
        path: "\\\\{{ hostvars['workstation_4']['ansible_host'] }}\\{{ stock_share_name }}"
        state: present

  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: '{{ content_user }}'
    ansible_become_pass: '{{ content_password }}'