---
# vars file for workstations

projects:
  - name: "{{ project_name }}"
    stages:
      - "Big Beast"
      - "Park"
      - "Sitewide"
      - "Stages"
      - "Tunnel"
      - "UG1 Plexi"
      - "UG2 Log"
      - "UG3 Port"
      - "UG4 Silk"