---
# tasks file for workstations
- include_tasks: "{{ workstations_tasks }}"
  loop:
    - create_project_folders.yml
    - create_content_users.yml
    - map_network_drives.yml
    - install_software.yml
  loop_control:
    loop_var: workstations_tasks
  when: workstations_tasks != 'map_network_drives.yml' or not (workstations_skip_drive_mapping | default(false))